#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define NBLIGNES 15
#define NBCOLS 15
#define POSLIGNE 5
#define POSCOL 10
#define N_COLONNES 31
#define N_LIGNES 16

#define BATTLESHIP_LENGTH 7
#define CRUISER_LENGTH 5
#define DESTROYER_LENGTH 3
#define SUBMARINE_LENGTH 1

#define UP 1
#define RIGHT 2
#define DOWN 3
#define LEFT 4

#endif // CONSTANTES_H_INCLUDED
